### ISSUE TITLE
Custom stacks are not showing up

### ISSUE THREAD

**Issue by 781227k** [eclipse/kuksa.ide#2]
I've build the system as described in the documentation and run it, but the custom stacks are not showing in the dashboard. 

I verified the custom build with following commands for stack customization and kuksa-stacks is not created in the api.war file, it still contains che-core-ide-stacks-$version

```
export TEMP_DIR=`mktemp -d`
cd <kuksa-ide-root-path>/assembly/assembly-main/target/eclipse-che-<version>/eclipse-che-<version>

# Copy to temp dir
cp tomcat/webapps/api.war ${TEMP_DIR}

# Change to temp dir
pushd ${TEMP_DIR}
jar xf api.war

tree | grep stacks
``

**Comment by rohoet** [comment]
After spending some time on this issue, I was able to fix it by sticking to Eclipse Che 6.10.0. 
In the meantime, Eclipse Che completely changed the plugin development structure from using GWT to using Eclipse Theia (which makes a lot of sense). Eclipse Kuksa.IDE plugins yet do not work with Che > v6.10.0.

I will include the fix on the master branch shortly.
For the future, it makes sense to rewrite the plugins in order to work with Che v7.x.
Currently, I cannot estimate when this will be tackled.
